version: '3.8'
services:
  autocomplete:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - CACHE_TTL=10m
      - LOG_LEVEL=debug
    depends_on:
      - redis
    volumes:
      - ./data:/app/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 